Repository adam-niggebrugge/emochat, pull requests merged in 2021-12, with the labels that each got.

#37 36 menu component
  client/public/menu.html
  client/src/App.css
  client/src/App.js
  client/src/components/menu/index.js
Labels: base components

#49 Check with apollo schema
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Context/ChatProvider.js
  client/src/Pages/Homepage.js
  client/src/components/Authentication/Login.js
  client/src/components/Authentication/Signup.js
  client/src/components/login/index.js
  client/src/components/miscellaneous/SideDrawer.js
  client/src/components/register/index.js
  client/src/utils/auth.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  package-lock.json
  server/config/connection.js
  server/controllers/userControllers.js
  server/models/chatModel.js
  server/models/messageModel.js
  server/models/userModel.js
  server/package-lock.json
  server/package.json
  server/routes/chatRoutes.js
  server/routes/messageRoutes.js
  server/routes/userRoutes.js
  server/schemas/index.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/server.js
Labels: enhancement

#51 50 graphql login register
  client/package-lock.json
  client/package.json
  client/src/.env
  client/src/App.js
  client/src/Pages/Homepage.js
  client/src/components/login/index.js
  client/src/components/register/index.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  package-lock.json
  package.json
  server/.env
  server/config/connection.js
  server/data/data.js
  server/middleware/auth21HW.js
  server/models/userModel.js
  server/package-lock.json
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/server.js
Labels: documentation

#54 52 fix contact names
  client/src/components/miscellaneous/GroupChatModal.js
  client/src/components/userAvatar/UserListItem.js
  server/config/connection.js
Labels: bug
