Repository adam-niggebrugge/emochat, pull requests merged in 2021-11, with the labels that each got.

#8 Initial installs
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: documentation

#10 Client server restructure
  .gitignore
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/.gitignore
  server/config/connection.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: enhancement

#17 15_DB_Models
  server/models/chatModel.js
  server/models/messageModel.js
  server/models/userModel.js
Labels: enhancement

#21 14 interactive background face
  client/src/App.js
  client/src/components/InteractiveEmoji/MousePosition.js
  client/src/components/InteractiveEmoji/README.md
  client/src/components/InteractiveEmoji/index.js
  client/src/components/InteractiveEmoji/style.css
Labels: enhancement

#23 22_chatController
  server/controllers/chatControllers.js
Labels: base components
